hostname: HQ-R2
ansible_host: 172.16.0.4
public_ip: 85.16.100.3
interfaces:
  layer3:
    - { name: GigabitEthernet0/0, ip: 172.16.0.4/31, nat: inside, ipv6_link_local_only: true, description: 'Link to HQ-MLS1' }
    - { name: GigabitEthernet1/0, ip: 172.16.0.6/31, nat: inside, ipv6_link_local_only: true, description: 'Link to HQ-MLS2' }
    - { name: GigabitEthernet2/0, ip: 85.16.100.3/31, nat: outside, ipv6: false, description: 'Link to ISP' }

access_lists:
  - { name: SD-ACL-internal-client, permit: [10.0.10.0/24, 10.0.15.0/24, 10.0.20.0/24, 10.0.25.0/24, 10.0.50.0/24, 10.0.51.0/24, 10.0.70.0/24, 10.0.200.0/24, 10.0.220.0/24] }
  - { name: SD-ACL-external-client, permit: [10.0.100.0/22, 10.0.104.0/22, 10.0.160.0/22] }

nat:
  overload_interfaces:
    - { acl: SD-ACL-internal-client, name: GigabitEthernet2/0 }
    - { acl: SD-ACL-external-client, name: GigabitEthernet2/0 }

dmvpn:
  role: hub
  tunnel:
     name: Tunnel0
     ip: 192.168.0.2/24

eigrp:
  router_id: 0.0.0.4
  networks: [172.16.0.4/31, 172.16.0.6/31, 192.168.0.0/24]
  non_passive_interfaces: [GigabitEthernet0/0, GigabitEthernet1/0, Tunnel0]
  redistribute_static: true

static_routes:
  ipv4:
    - { destination: 0.0.0.0/0, via: 85.16.100.3}
  ipv6:
    - { destination: "::/0", via: GigabitEthernet2/0 }