hostname: Szf-R
ansible_host: 82.1.79.129
public_ip: 82.1.79.129
interfaces:
  layer3:
    - { name: GigabitEthernet0/0, ip: 82.1.79.129/28, nat: outside, ipv6: 2a:1dc:7c0:01FF:82:1:79:129/64, description: 'Link to ISP' }

  vlan:
    - { id: 10, ip: 10.1.10.1/24, description: 'VLAN 10', port: GigabitEthernet1/0  }
    - { id: 20, ip: 10.1.20.1/24, description: 'VLAN 20', port: GigabitEthernet1/0  }
    - { id: 50, ip: 10.1.50.1/24, description: 'VLAN 50', port: GigabitEthernet1/0  }
    - { id: 110, ip: 10.1.110.1/22, description: 'VLAN 110', port: GigabitEthernet1/0 }
    - { id: 252, ip: 10.1.252.1/22, description: 'VLAN 252', port: GigabitEthernet1/0 }

access_lists:
  - { name: SD-ACL-internal-client, permit: [10.1.10.0/24, 10.1.20.0/24, 10.1.50.0/24, 10.1.110.0/24, 10.1.252.0/24] }
  - { name: SD-ACL-external-client, permit: [10.1.120.0/24] }

nat:
  pools:
    - { name: SD-internal-client-pool, range: { start: 82.1.79.129, end: 82.1.79.134 }, netmask: 255.255.255.248, acl: SD-ACL-internal-client, overload: true }
    - { name: SD-external-client-pool, range: { start: 82.1.79.137, end: 82.1.79.142 }, netmask: 255.255.255.248, acl: SD-ACL-external-client, overload: true }

dmvpn:
  role: spoke
  tunnel:
    name: Tunnel0
    ip: 192.168.0.3/24

eigrp:
  router_id: 0.1.0.1
  networks: [10.1.10.0/24, 10.1.20.0/24, 10.1.50.0/24, 10.1.110.0/22, 10.1.252.0/22, 192.168.0.0/24]
  non_passive_interfaces: [GigabitEthernet0/0, GigabitEthernet1/0, Tunnel0]
  redistribute_static: true

static_routes:
  ipv4:
    - { destination: 0.0.0.0/0, via: 82.1.79.142 }
  ipv6:
    - { destination: "::/0", via: GigabitEthernet0/0}