hostname: HQ-MLS2
ansible_host: 10.0.253.2

spanning_tree_primary: [10, 15, 20, 50, 100, 160, 255]
spanning_tree_secondary: [70, 200]

# GNS3 tesztelős konfig
vtp_mode: 'client'
lacp:
  - { interfaces: FastEthernet0/23-24, switchport: false, mode: active, channel_group: 1 }
  - { interfaces: FastEthernet0/21-22, switchport: true,  mode: active, channel_group: 2 }

interfaces:
  layer3:
    - { name: FastEthernet0/1, ip: 172.16.0.3/31, ipv6_link_local_only: true, description: 'Link to HQ-R1' }
    - { name: FastEthernet0/2, ip: 172.16.0.7/31, ipv6_link_local_only: true, description: 'Link to HQ-R2' }
    - { name: Port-channel 1,     ip: 172.16.0.9/31, ipv6_link_local_only: true, description: 'Layer 3 link to MLS1' }

  layer2:
    - { name: FastEthernet0/3, mode: trunk,  encapsulation: dot1q,  allowed_vlans: [10, 15, 100, 220, 200, 252], description: 'Link to HQ-OFFICE-S1' }
    - { name: FastEthernet0/4, mode: trunk,  encapsulation: dot1q,  allowed_vlans: [20, 25, 100, 160, 200, 252], description: 'Link to HQ-OFFICE-S2' }
    - { name: FastEthernet0/5, mode: trunk,  encapsulation: dot1q,  allowed_vlans: [50, 104, 200, 252],          description: 'Link to HQ-WS-S1' }
    - { name: FastEthernet0/6, mode: trunk,  encapsulation: dot1q,  allowed_vlans: [51, 104, 200, 252],          description: 'Link to HQ-WS-S2' }
    - { name: FastEthernet0/13, mode: access, access_vlan: 70,      description: 'Link to SD-HQ-PVE1 (and all other HQ server by extension)' }
    
    - { name: Port-channel 2,     mode: trunk,  encapsulation: dot1q, description: 'Layer 2 link to MLS1' }

vlan_interfaces:
  # HSRP group and IPv6 are inferred
  # Read by playbooks/roles/cisco-config/templates/vlan_interface.j2.
  - { id: 10,  ip: 10.0.10.2/24,  hsrp_priority: 110 }
  - { id: 15,  ip: 10.0.15.2/24,  hsrp_priority: 110 }
  - { id: 20,  ip: 10.0.20.2/24,  hsrp_priority: 110 }
  - { id: 25,  ip: 10.0.25.2/24,  hsrp_priority: 110 }
  - { id: 50,  ip: 10.0.50.2/24,  hsrp_priority: 110 }
  - { id: 51,  ip: 10.0.51.2/24,  hsrp_priority: 110 }
  - { id: 70,  ip: 10.0.70.2/24,  hsrp_priority: 90 }
  - { id: 100, ip: 10.0.100.2/22, hsrp_priority: 110 }
  - { id: 104, ip: 10.0.104.2/24, hsrp_priority: 110 }
  - { id: 160, ip: 10.0.160.2/22, hsrp_priority: 110 }
  - { id: 200, ip: 10.0.200.2/24, hsrp_priority: 90 }
  - { id: 220, ip: 10.0.220.2/24, hsrp_priority: 110 }
  - { id: 252, ip: 10.0.253.2/22, hsrp_priority: 110 }

eigrp:
  router_id: 2.2.2.2
  networks: [10.0.0.0/16, 172.16.0.2/31, 172.16.0.6/31, 172.16.0.8/31]
  non_passive_interfaces: [FastEthernet0/0, FastEthernet0/1, Port-channel 1]