hostname: HQ-OFFICE-S2
ansible_host: 10.0.254.2

interfaces:
  layer2:
  - { name: GigabitEthernet0/1, mode: trunk, encapsulation: dot1q, dhcp_snooping: { trust: true }, description: 'Link to HQ-MLS-1' }
  - { name: GigabitEthernet0/2, mode: trunk, encapsulation: dot1q, dhcp_snooping: { trust: true }, description: 'Link to HQ-MLS-2' }
  - { name: FastEthernet0/1, mode: access, access_vlan: 160, dhcp_snooping: { limit_rate: 50, trust: false }, description: 'VLAN 160: Vendeg WAN' }
  - { name: FastEthernet0/2, mode: access, access_vlan: 100, dhcp_snooping: { limit_rate: 50, trust: false }, description: 'VLAN 100: Iroda WAN' }
  - { name: FastEthernet0/3, mode: access, access_vlan: 20, dhcp_snooping: { trust: false }, voice: false, description: 'VLAN 20: Marketing' }
  - { name: FastEthernet0/4, mode: access, access_vlan: 25, dhcp_snooping: { trust: false }, voice: false, description: 'VLAN 25: Ertekesites' }

  vlan:
    - { id: 252, ip: 10.0.254.2/22 }
