hostname: HQ-WS-S1
ansible_host: 10.0.254.3

interfaces:
  layer2:
  - { name: GigabitEthernet0/1, mode: trunk, encapsulation: dot1q, dhcp_snooping: { trust: true }, description: 'Link to HQ-MLS-1' }
  - { name: GigabitEthernet0/2, mode: trunk, encapsulation: dot1q, dhcp_snooping: { trust: true }, description: 'Link to HQ-MLS-2' }
  - { name: FastEthernet0/1, mode: access, access_vlan: 50, dhcp_snooping: { trust: false }, voice: false, description: 'VLAN 50: Fejlesztok 1' }
  - { name: FastEthernet0/2, mode: access, access_vlan: 104, dhcp_snooping: { limit_rate: 50, trust: false }, description: 'VLAN 104: Workshop WAN' }

  vlan:
    - { id: 252, ip: 10.0.254.3/22 }
