---
all:
    vars:
        company_name: "Solar Dynamics"
        domain_name: solardynamics.eu
        admin_name: "solaire"

    children:
        linux_servers:
            hosts:
                SD-HQ-LIN1:
                # Variables in ./host_vars/SD-HQ-LIN1.yaml
                
                SD-HQ-NMS:
                # Variables in ./host_vars/SD-HQ-NMS.yaml

                SD-HQ-PVE1:
                # Variables in /inventory/host_vars/SD-HQ-PVE1.yaml

        windows_servers:
            # Group-wide variables in /inventory/group_vars/windows_servers.yaml
            hosts:
                SD-HQ-WIN1:
                # Variables in /inventory/host_vars/SD-HQ-WIN1.yaml

        proxmox_servers:
            hosts:
                SD-HQ-PVE1:
                # Variables in /inventory/host_vars/SD-HQ-PVE1.yaml

        cisco:
            # Group-wide variables in /inventory/group_vars/cisco.yaml
            children:
                routers:
                    hosts:
                        HQ-R1:
                            ansible_host: 82.136.79.1
                        HQ-R2:
                            # ansible_host: 82.136.79.2
                            ansible_host: 85.16.100.3
                mls:
                    hosts:
                        HQ-MLS1:
                            ansible_host: 10.0.252.1
                        HQ-MLS2:
                            ansible_host: 10.0.252.2
                switches:
                    hosts:
                        HQ-OFFICE-S1:
                            ansible_host: 10.0.254.1
                        HQ-OFFICE-S2:
                            ansible_host: 10.0.254.2
                        HQ-WS-S1:
                            ansible_host: 10.0.254.3
                        HQ-WS-S2:
                            ansible_host: 10.0.254.4
                        SzF_SW:
                            ansible_host: 110.1.252.2
                        SzF_SW2:
                            ansible_host: 10.1.252.3
                        TB-EM2-IRODA:
                            ansible_host: 10.3.252.3
                        TB-EM1-LOGI:
                            ansible_host: 10.3.252.2
                        TB-EM3-PARTNER:
                            ansible_host: 10.3.252.4

        hq:
            vars:
                domain_name: hq.solardynamics.eu

            hosts:
                SD-HQ-LIN1:
                SD-HQ-WIN1:
                HQ-R1:
                    ansible_host: 82.136.79.1
                HQ-R2:
                    ansible_host: 82.136.79.2
                HQ-MLS1:
                    ansible_host: 10.0.252.1
                HQ-MLS2:
                    ansible_host: 10.0.252.2
                HQ-OFFICE-S1:
                    ansible_host: 10.0.254.1
                HQ-OFFICE-S2:
                    ansible_host: 10.0.254.2
                HQ-WS-S1:
                    ansible_host: 10.0.254.3
                HQ-WS-S2:
                    ansible_host: 10.0.254.4

        szf:
            vars:
                domain_name: szf.solardynamics.eu

            hosts:
                SzF_R:
                    ansible_host: 10.1.252.1
                SzF_SW:
                    ansible_host: 110.1.252.2
                SzF_SW2:
                    ansible_host: 10.1.252.3
                SzF_WR:
                    ansible_host: 10.1.110.2

        tb:
            vars:
                domain_name: tb.solardynamics.eu

            hosts:
                TB-RT:
                    ansible_host: 10.3.252.1
                TB-EM2-IRODA:
                    ansible_host: 10.3.252.3
                TB-EM1-LOGI:
                    ansible_host: 10.3.252.2
                TB-EM3-PARTNER:
                    ansible_host: 10.3.252.4
                TB-WIFI-VARO:
                    ansible_host: 10.3.150.2


        bp:
            vars:
                domain_name: bp.solardynamics.eu
...
