---
# === Common ===
- name: Backup current config to control node
  cisco.ios.ios_config:
    backup: true
    backup_options:
      dir_path: "{{ lookup('env', 'HOME') }}/cisco_backup"
  register: backup_ios_location

- name: Configure hostname and domain
  cisco.ios.config:
    commands:
      - hostname {{ hostname }}
      - ip domain name {{ domain_name }}
    diff_against: running

- name: Configure banners
  cisco.ios.ios_config:
    commands:
      - banner login \#{{ banner_text }}\#
      - banner incoming \#{{ banner_text }}\#
      - banner exec \#{{ banner_text }}\#
    diff_against: running

- name: Configure NTP server
  cisco.ios.ios_config:
    commands:
      - ntp server ip {{ ntp_server }}
    diff_against: running

- name: Conifgure DNS server
  cisco.ios.ios_config:
    commands:
      - ip name-server {{ dns_servers[0] }} {{ dns_servers[1] }}
    diff_against: running

- name: Enable IP domain lookup
  cisco.ios.ios_config:
    commands:
      - "ip domain lookup"
    diff_against: running

# === Device specific ===
- name: Configure routers
  ansible.builtin.include_tasks: routers.yaml
  when: "'routers' in group_names"
  tags:
    -interface

- name: Configure mls
  ansible.builtin.include_tasks: mls.yaml
  when: "'mls' in group_names"
  tags:
    - interface

- name: Configure switches
  ansible.builtin.include_tasks: switches.yaml
  when: "'switches' in group_names"
  tags:
    - interface

- name: Save configurations
  cisco.ios.ios_command:
    commands:
      - "write memory"

- name: Print backup location
  ansible.builtin.debug:
    msg: "Backup location: {{ backup_ios_location }}"


...
