- name: Configure VTP
  cisco.ios.ios_config:
    src: vtp.j2

- name: Configure STP
  cisco.ios.ios_config:
    src: stp.j2

- name: Configure Etherchannels
  cisco.ios.ios_config:
    src: etherchannel.j2
  when: lacp is defined

- name: Configure VLANs
  cisco.ios.ios_config:
    src: vlans.j2
  when: vtp_mode is defined and vtp_mode == 'server'

- name: Configure interfaces
  vars:
    ansible_command_timeout: 60
  cisco.ios.ios_config:
    src: interface.j2
    diff_against: running
  when: interfaces is defined
  tags: interface

#- name: Configure VLAN interfaces
#  cisco.ios.ios_config:
#    src: vlan_interface.j2
#  when: interfaces.vlan is defined
#  tags: interface

- name: Configure default gateway
  cisco.ios.config:
    commands:
      - ip default-gateway {{ site_vlans | selectattr('id', 'equalto', 252) | first | map(attribute='network') | first | ipaddr('last_usable') }}
