- name: Read users CSV
  community.general.read_csv:
    path: "{{ create_users_csv }}"
  register: user_list
  delegate_to: SD-HQ-NMS

- name: Add users
  ansible.builtin.user:
    name: "{{ item.SamAccountName }}"
    comment: "{{ item.DisplayName | default('') }}"
    update_password: on_create
    password: "{{ item.Password | password_hash('sha512') }}"
    append: true
    groups: "ansible"
    create_home: true
  loop: "{{ user_list.list }}"
  loop_control:
    label: "{{ item.SamAccountName }}"

- name: Create Maildir for each user
  ansible.builtin.file:
    path: "/home/{{ item.0.SamAccountName }}/Maildir/{{ item.1 }}"
    state: directory
    owner: "{{ item.0.SamAccountName }}"
    group: "{{ item.0.SamAccountName }}"
    mode: "0700"
  loop: "{{ user_list.list | product(maildir_subdirs) | list }}"
  vars:
    maildir_subdirs:
      - ""
      - "cur"
      - "new"
      - "tmp"
  loop_control:
    label: "{{ item.0.SamAccountName }}/{{ item.1 }}"
