- name: Read users CSV
  community.general.read_csv:
    path: "{{ create_users_csv }}"
  register: user_list
  delegate_to: SD-HQ-NMS

- name: Add users
  ansible.builtin.user:
    name: "{{ item.SamAccountName }}"
    comment: "{{ item.DisplayName | default('') }}"
    password: "{{ item.Password | password_hash('sha512') }}"
    append: true
    groups: "ansible"
    create_home: true
    update_password: on_create
  loop: "{{ user_list.list }}"
  loop_control:
    label: "{{ item.SamAccountName }}"
