- name: Install Dovecot packages
  ansible.builtin.apt:
    name:
      - dovecot-core
      - dovecot-imapd
    state: present
    update_cache: true

- name: Configure Dovecot main
  ansible.builtin.template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dovecot

- name: Configure Dovecot mail settings
  ansible.builtin.template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dovecot

- name: Configure Dovecot authentication
  ansible.builtin.template:
    src: 10-auth.conf.j2
    dest: /etc/dovecot/conf.d/10-auth.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dovecot

- name: Configure Dovecot master services
  ansible.builtin.template:
    src: 10-master.conf.j2
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dovecot

- name: Ensure Dovecot is running
  ansible.builtin.service:
    name: dovecot
    state: started
    enabled: true
