---
# Install Nginx and PHP packages
- name: Install Nginx and PHP packages
  become: true
  apt:
    name:
      - nginx
      - php
      - php-pgsql
    state: present

# Start and enable Nginx
- name: Start and enable nginx
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx

- name: Configure nginx for Zabbix frontend
  become: true
  lineinfile:
    path: /etc/zabbix/nginx.conf
    regexp: '^(# )?(listen|server_name)'
    line: "{{ item }}"
    state: present
  loop:
    - 'listen 8080;'
    - 'server_name {{ zabbix_server_name }};'
  notify: Restart nginx
  
# Ensure all Zabbix Services are Started and Enabled
- name: Ensure all Zabbix Services are Started and Enabled
  become: true
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - zabbix-server
    - zabbix-agent
    - nginx