---
# Install Nginx
- name: Install Nginx
  become: true
  apt:
    name:
      - nginx
      - php
      - php-pgsql
    state: present

- name: Configure listen directive for Zabbix frontend
  become: true
  lineinfile:
    path: /etc/zabbix/nginx.conf
    regexp: '^\s*(#\s*)?listen'
    line: 'listen 8080;'
    state: present
  notify: Restart nginx

- name: Configure server_name directive for Zabbix frontend
  become: true
  lineinfile:
    path: /etc/zabbix/nginx.conf
    regexp: '^\s*(#\s*)?server_name'
    line: 'server_name {{ zabbix_server_name }};'
    state: present
  notify: Restart nginx


# Start and enable Nginx
- name: Start and enable nginx
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx


  
# Ensure all Zabbix Services are Started and Enabled
- name: Ensure all Zabbix Services are Started and Enabled
  become: true
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - zabbix-server
    - zabbix-agent
    - nginx