---
# === PostgreSQL ===
- name: Install PostgreSQL
  become: true
  apt:
    name: postgresql
    state: present

- name: Start and enable postgresql
  become: true
  service:
    name: postgresql
    state: started
    enabled: yes

# Set up the permissions in the file
- name: Switch local 'postgres' user from peer to trust
  become: true
  lineinfile:
    path: /etc/postgresql/{{ postgresql_version_number }}/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres\s+peer'
    line: 'local   all   postgres                 trust'
    backup: yes

- name: Switch local zabbix from peer to trust )
  become: true  
  lineinfile:
    path: /etc/postgresql/{{ postgresql_version_number }}/main/pg_hba.conf
    regexp: '^local\s+all\s+all\s+peer'
    line: 'local   all   {{ zabbix_db_user }}                       trust'
    backup: yes
  notify: Restart postgresql

- name: Execute pending handlers
  meta: flush_handlers

# Set PostgreSQL password for user 'postgres'
- name: Set PostgreSQL password for 'postgres' user
  become: true
  postgresql_user:
    name: postgres
    password: "{{ postgresql_password }}"


# Unused as of now pretty much
- name: Configure PostgreSQL to use trust authentication for localhost and zabbix user
  become: true
  blockinfile:
    path: "{{ pg_hba_conf_path }}"
    block: |
      local   all             postgres                                trust
      local   all             {{ zabbix_db_user }}                    trust
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    state: present
  notify: Restart postgresql


