# --- Zabbix repo configuration ---
- name: Download Zabbix release package
  become: true
  get_url:
    url: "{{ zabbix_release_url }}"
    dest: "{{ zabbix_release_deb_path }}"

- name: Install Zabbix release package
  become: true
  apt:
    deb: "{{ zabbix_release_deb_path }}"

- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: true
    
# --- Zabbix Installation ---
- name: Install Zabbix server and frontend
  become: true
  apt:
    name:
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php8.2-pgsql
      - zabbix-nginx-conf
      - zabbix-sql-scripts
      - zabbix-agent
    state: present

- name: Ensure SNMP Trapper is enabled in Zabbix configuration
  become: true
  lineinfile:
    path: "{{ zabbix_conf_file }}"
    regexp: "^#?StartSNMPTrapper="
    line: "StartSNMPTrapper=1"
    state: present
  notify: Restart Zabbix Server

- name: Ensure SNMP Trapper file is configured
  become: true
  lineinfile:
    path: "{{ zabbix_conf_file }}"
    regexp: "^#?SNMPTrapperFile="
    line: "SNMPTrapperFile={{ snmp_trapper_file }}"
    state: present
  notify: Restart Zabbix Server

- name: Ensure the SNMP Trapper file exists
  become: true
  file:
    path: "{{ snmp_trapper_file }}"
    state: touch
    owner: zabbix
    group: zabbix
    mode: '0644'

# --- Zabbix Database Configuration ---
- name: Create Zabbix user in PostgreSQL
  become: true
  postgresql_user:
    name: "{{ zabbix_db_user }}"
    password: "{{ zabbix_db_password }}"
    state: present

- name: Create Zabbix server database
  become: true
  postgresql_db:
    name: "{{ zabbix_db_name }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    owner: "{{ zabbix_db_user }}"
  register: zabbix_db_creation

- name: Grant all privileges on zabbix database to zabbix user
  become: true
  postgresql_privs:
    db: "{{ zabbix_db_name }}"
    type: database
    privs: ALL
    role: "{{ zabbix_db_user }}"
    state: present

- name: Import Zabbix schema into PostgreSQL
  ansible.builtin.shell: |
    zcat /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz | sudo -u {{ zabbix_db_user }} psql {{ zabbix_db_name }}
  changed_when: false

- name: Update Zabbix Server Configuration with Database Credentials
  become: true
  blockinfile:
    path: /etc/zabbix/zabbix_server.conf
    marker: "# {mark} MANAGED BLOCK"
    block: |
      DBPassword={{ zabbix_db_password }}
    state: present
  notify: Restart Zabbix Server
# Configure PostgreSQL to Allow Database Connections
#- name: Modify PostgreSQL configuration for Zabbix
#  ansible.builtin.shell: |
#    sed -i 's/ident/md5/' {{ pg_hba_conf_path }}

#  changed_when: false

# Configure PostgreSQL to Allow Database Connections
- name: Ensure pg_hba.conf allows connections from localhost
  become: true
  lineinfile:
    path: "{{ pg_hba_conf_path }}"
    regexp: '^host\s+zabbix\s+zabbix\s+127.0.0.1/32\s+md5'
    line: 'host    zabbix          zabbix          127.0.0.1/32            md5'
    state: present
  notify: Reload postgresql