---
- name: Ensure SSL directory exists
  file:
    path: "{{ webserver_ssl_cert_path | dirname }}"
    state: directory
    mode: '0755'

- name: Generate a private key for NGINX SSL
  openssl_privatekey:
    path: "{{ webserver_ssl_key_path }}"
    size: 2048
    state: present
  register: ssl_key

- name: Generate a self-signed certificate for NGINX
  openssl_certificate:
    path: "{{ webserver_ssl_cert_path }}"
    privatekey_path: "{{ webserver_ssl_key_path }}"
    common_name: "{{ webserver_ssl_common_name }}"
    provider: selfsigned
    days: "{{ webserver_ssl_days }}"
  register: ssl_cert
