- name: Ensure OpenSSL is installed
  ansible.builtin.package:
    name: openssl
    state: present

- name: Create SSL directory
  ansible.builtin.file:
    path: "{{ ssl_directory }}"
    state: directory
    owner: root
    group: "{{ nginx_group }}"
    mode: '0750'

- name: Generate SSL private key
  community.crypto.openssl_privatekey:
    path: "{{ webserver_ssl_key_path }}"
    owner: root
    group: www-data
    mode: '0640'

- name: Generate self-signed SSL certificate
  community.crypto.x509_certificate:
    path: "{{ webserver_ssl_cert_path }}"
    privatekey_path: "{{ webserver_ssl_key_path }}"
    provider: selfsigned
    force: false

- name: Set certificate permissions
  ansible.builtin.file:
    path: "{{ webserver_ssl_cert_path }}"
    owner: root
    group: www-data"
    mode: '0640'
