- name: Ensure OpenSSL is installed
  ansible.builtin.package:
    name: openssl
    state: present

- name: Generate SSL private key
  community.crypto.openssl_privatekey:
    path: "{{ webserver_ssl_key_path }}"


# This takes too long, and is not necessary (https://www.howtogeek.com/devops/how-to-create-and-use-self-signed-ssl-on-nginx/)

# - name: Create DH group
#   community.crypto.openssl_dhparam:
#     path: {{ webserver_dhparam_path }}
#     size: 4096
#     state: present

- name: Generate self-signed SSL certificate
  community.crypto.x509_certificate:
    path: "{{ webserver_ssl_cert_path }}"
    privatekey_path: "{{ webserver_ssl_key_path }}"
    provider: selfsigned
    force: false