---
- name: Restart Zabbix Server
  systemd:
    name: zabbix-server
    state: restarted

- name: Restart Zabbix Agent
  systemd:
    name: zabbix-agent
    state: restarted

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted

- name: Reload PostgreSQL
  systemd:
    name: postgresql
    state: reloaded

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted