---
- name: Restart Zabbix Server
  become: true
  service:
    name: zabbix-server
    state: restarted

- name: Restart Zabbix Agent
  become: true
  service:
    name: zabbix-agent
    state: restarted

- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted

- name: Reload postgresql
  become: true
  service:
    name: postgresql
    state: reloaded

- name: Restart postgresql
  become: true
  service:
    name: postgresql
    state: restarted