---
- name: SD-HQ-LIN1 configuration
  hosts: SD-HQ-LIN1
  gather_facts: true 
  become: true
  roles:
    - webserver
    - zabbix-agent
    - resolv.conf
    - ntp

- name: SD-HQ-LIN2 configuration
  hosts: SD-HQ-LIN2
  gather_facts: true 
  become: true
  roles:
    - mail
    - zabbix-agent
    - resolv.conf
    - ntp

...
