---
- name: SD-HQ-LIN1 configuration
  hosts: SD-HQ-LIN1
  gather_facts: true 
  become: true
  roles:
    - ntp # This will be a server
    - webserver

- name: SD-HQ-LIN2 configuration
  hosts: SD-HQ-LIN2
  gather_facts: true 
  become: true
  roles:
    - ftp
    - mail

...
