---
# Playbook: debian-basic-setup.yaml
# Description: Basic setup for Debian systems, including installing essential packages, configuring sudo, and other base configurations.
- name: Basic setup for Debian systems
  hosts: linux_servers
  become: true  # Run with elevated privileges
  vars:
    # Pulled from the hosts.yaml file
    admin_username: "{{ admin_name }}"
  tasks:

    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600  # 1 hour

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true

    - name: Install essential packages
      ansible.builtin.apt:
        name:
          - sudo
        state: present

    - name: Ensure the firewall (UFW) is installed
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Enable SSH service
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: true

    - name: Allow OpenSSH
      community.general.ufw:
        rule: allow
        name: OpenSSH

    # Right now we are not using the firewall
    - name: Disable the firewall (UFW)
      community.general.ufw:
        state: disabled

    - name: Add the user to the sudo group
      ansible.builtin.user:
        name: "{{ admin_name }}"
        groups: sudo
        append: true

    - name: Verify user is part of the sudo group
      ansible.builtin.command: id "{{ admin_name }}"
      register: user_check
      changed_when: false

    - name: Display user group information
      ansible.builtin.debug:
        msg: "User '{{ admin_name }}' is in groups: {{ user_check.stdout }}"
        
    # This is run after the rest of the playbook
    # All Linux servers will have zabbix-agent, resolv.conf configured, and chrony client (or server) configured and installed.

    - name: Configure ntp
      ansible.builtin.include_role:
        name: ntp

    - name: Install zabbix-agent
      ansible.builtin.include_role:
        name: zabbix-agent
        
    - name: Configure DNS
      ansible.builtin.include_role:
        name: resolv.conf
