---
- name: Install sudo
  hosts: linux_servers
  tasks:
    - name: Ping Linux servers
      ping:

- name: Install sudo
  hosts: linux_servers
  tasks:
    - name: Ping Linux servers
      ping:

- name: Install sudo
  hosts: linux_servers
  tasks:
    - name: Ping Linux servers
      ping:

  

...
