---
- name: NMS configuration
  hosts: SD-HQ-NMS
  gather_facts: false # localhoston fut, úgyhogy nem kell.
  become: true # Alapból a manager felhasználóval (nálunk ez solaire) futtatjuk a taskokat, ahol root kell ott expliciten megadjuk

  # Globális változók, frissítések esetén kell ezeket változtatni
  vars:
    ssh_key_path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

  # Nessus letöltés
    nessus_download_url: "https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-10.8.3-debian10_amd64.deb"
    nessus_deb_path: "/tmp/nessus.deb"

  tasks:
    # === BASIC SETUP ===

    # --- SSH Key Management configuration ---
    - name: Check if SSH key pair already exists
      ansible.builtin.stat:
        path: "{{ ssh_key_path }}"
      register: ssh_key_status

    - name: Generate SSH key pair if not present
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_path }}"
        type: rsa
        size: 2048
        mode: '0600'
      when: not ssh_key_status.stat.exists
      notify: Display public key content

    # --- Essential Packages Installation ---
    - name: Install essential packages
      become: true
      ansible.builtin.apt:
        name:
          - sudo
        state: present

    - name: Install essential Ansible modules with pip to the venv
      ansible.builtin.pip:
        name:
          # This is for better SSH support
          - ansible-pylibssh
          # This is for postgresql
          - psycopg2-binary
          # This is for tempalting subnet masks easier
          - netaddr
        virtualenv: "{{ lookup('env', 'HOME') }}/ansible-venv"

    # === NESSUS ===
    # --- Nessus Installation ---
    # DPKG-t kell használni, mert alapból nincs a repositorykban a nessus, és .deb fileból telepítjük
    - name: Check if nessus is installed
      ansible.builtin.command: dpkg-query -W nessus
      register: nessus_missing
      failed_when: nessus_missing.rc > 1
      changed_when: nessus_missing.rc == 1

    - name: Download nessus
      ansible.builtin.get_url:
        url: "{{ nessus_download_url }}"
        dest: "{{ nessus_deb_path }}"
        mode: '0777'
      when: nessus_missing.rc == 1

    - name: Install nessus
      become: true
      ansible.builtin.apt:
        deb: "{{ nessus_deb_path }}"
      when: nessus_missing.rc == 1

    - name: Enable and start nessus
      become: true
      ansible.builtin.service:
        name: nessusd
        enabled: true
        state: started

    - name: Install Zabbix
      ansible.builtin.include_role:
        name: zabbix-install

  handlers:
    - name: Display public key content
      ansible.builtin.debug:
        msg: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
