---
- name: NMS configuration
  hosts: SD-HQ-NMS
  gather_facts: no
  become: no  # Run with elevated privileges
  vars:
    # Vars for installing Nessus
    nessus_download_url: "https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-10.8.3-debian10_amd64.deb"
    nessus_download_name: "nessus"


  tasks:
    - name: Check if SSH key pair already exists
      stat:
        path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
      register: ssh_key_status

    - name: Generate SSH key pair if not present
      openssh_keypair:
        path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
        type: rsa
        size: 2048
        mode: '0600'
      when: not ssh_key_status.stat.exists
      register: ssh_keypair_result

    - name: Show message if SSH key already exists
      debug:
        msg: "SSH key pair already exists at {{ lookup('env', 'HOME') }}/.ssh/id_rsa"
      when: ssh_key_status.stat.exists

    - name: Display public key content
      debug:
        msg: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
      when: ssh_key_status.stat.exists or ssh_keypair_result is changed

    - name: Check if nessus is installed
      command: dpkg-query -W nessus
      register: nessus_check_deb
      failed_when: nessus_check_deb.rc > 1
      changed_when: nessus_check_deb.rc == 1

    - name: Download nessus
      get_url: 
        url="{{ nessus_download_url }}"
        dest="{{ lookup('env', 'HOME') }}/{{ nessus_download_name }}.deb"
      when: nessus_check_deb.rc == 1

    - name: Install nessus
      apt: deb="{{ lookup('env', 'HOME') }}/{{ nessus_download_name }}.deb"
      become: yes
      when: nessus_check_deb.rc == 1

    - name: Enable nessus
      become: yes
      service:
        name: nessusd
        enabled: yes

    - name: Start nessus
      become: yes
      service:
        name: nessusd
        state: started

    - name: Install essential packages
      become: yes
      apt:
        name:
          - sudo
          - pip
          - ansible-pylibssh
        state: present
...
