---
- name: NMS configuration
  hosts: linux_servers
  gather_facts: no
  become: yes  # Run with elevated privileges
  tasks:
    - name: Check if SSH key pair already exists
      stat:
        path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
      register: ssh_key_status

    - name: Generate SSH key pair if not present
      openssh_keypair:
        path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
        type: rsa
        size: 2048
        mode: '0600'
      when: not ssh_key_status.stat.exists
      register: ssh_keypair_result

    - name: Show message if SSH key already exists
      debug:
        msg: "SSH key pair already exists at {{ lookup('env', 'HOME') }}/.ssh/id_rsa"
      when: ssh_key_status.stat.exists

    - name: Display public key content
      debug:
        msg: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
      when: ssh_key_status.stat.exists or ssh_keypair_result is changed
...
