---
- name: Ping Windows server from Cisco devices
  hosts: cisco
  tasks:
    - name: Ping control node by IP
      cisco.ios.ios_ping:
        dest: 10.0.70.20
      
- name: Ping Windows server from Cisco devices
  hosts: cisco
  tasks:
    - name: Ping control node by IP
      ping:
        dest: 10.0.70.20

- name: Ping Windows server from Cisco by hostname
  hosts: cisco
  tasks:
    - name: Ping control node by IP
      ping:
        dest: SD-HQ-WIN1.solardynamics.eu

...

