---
- name: Ping Windows server from all devices
  hosts: linux_servers, cisco
  tasks:
    - name: Ping Linux servers
      ansible.builtin.ping:
        dest: 10.0.70.20    

- name: Ping SD-HQ-WIN1.solardynamics.eu from all devices 
  hosts: linux_servers, cisco
  tasks:
    - name: Ping Linux servers
      ansible.builtin.ping:
        dest: SD-HQ-WIN1.solardynamics.eu

...
