---
- name: Ping IP addresses from Cisco devices
  hosts: cisco
  gather_facts: false
  vars:
    ipaddresses:
      - 1.1.1.1
      - 10.0.70.20
      - 10.0.70.10
      - 10.0.70.11
      - 10.0.70.12
  tasks:
    - name: Send ping command from Cisco device
      cisco.ios.ios_command:
        commands:
          - "ping {{ item }}"
      loop: "{{ ipaddresses }}"
      register: cisco_ping
      ignore_errors: true

    - name: Build Cisco ping summary fact
      set_fact:
        ping_results_summary: >-
          {{
            (ping_results_summary | default([])) +
            [ {
                "source": inventory_hostname,
                "destination": item.0,
                "status": ( "SUCCESS" if (item.1.rc is defined and item.1.rc == 0) else "FAIL" )
              } ]
          }}
      loop: "{{ ipaddresses | zip(cisco_ping.results) | list }}"

- name: Ping IP addresses from Linux servers
  hosts: linux_servers
  gather_facts: false
  vars:
    ipaddresses:
      - 1.1.1.1
      - 10.0.70.20
      - 10.0.70.10
      - 10.0.70.11
      - 10.0.70.12
  tasks:
    - name: Send ping command from Linux server
      ansible.builtin.command: "ping -c 2 -W 1 {{ item }}"
      loop: "{{ ipaddresses }}"
      register: linux_ping
      ignore_errors: true

    - name: Build Linux ping summary fact for IPs
      set_fact:
        ping_results_summary: >-
          {{
            (ping_results_summary | default([])) +
            [ {
                "source": inventory_hostname,
                "destination": item.0,
                "status": ( "SUCCESS" if item.1.rc == 0 else "FAIL" )
              } ]
          }}
      loop: "{{ ipaddresses | zip(linux_ping.results) | list }}"

- name: Ping hostnames from Linux servers
  hosts: linux_servers
  gather_facts: false
  vars:
    hostnames:
      - SD-HQ-WIN1.solardynamics.eu
  tasks:
    - name: Send ping command for hostnames from Linux server
      ansible.builtin.command: "ping -c 2 -W 1 {{ item }}"
      loop: "{{ hostnames }}"
      register: hostname_ping
      ignore_errors: true

    - name: Build Linux ping summary fact for hostnames
      set_fact:
        ping_results_summary: >-
          {{
            (ping_results_summary | default([])) +
            [ {
                "source": inventory_hostname,
                "destination": item.0,
                "status": ( "SUCCESS" if item.1.rc == 0 else "FAIL" )
              } ]
          }}
      loop: "{{ hostnames | zip(hostname_ping.results) | list }}"

- name: Aggregate all ping results and write CSV files
  hosts: SD-HQ-NMS
  gather_facts: false
  tasks:
    - name: Aggregate ping summaries from all hosts
      set_fact:
        all_ping_results: >-
          {{
            all_ping_results | default([]) +
            ( hostvars[item].ping_results_summary | default([]) )
          }}
      loop: "{{ groups['cisco'] + groups['linux_servers'] }}"
      run_once: true

    - name: Write all ping results to CSV file
      copy:
        dest: "~/ping_results.csv"
        content: |
          source,destination,result
          {% for result in all_ping_results %}
          {{ result.source }},{{ result.destination }},{{ result.status }}
          {% endfor %}
      run_once: true

    - name: Write failed ping results to CSV file
      copy:
        dest: "~/failed_ping_results.csv"
        content: |
          source,destination,result
          {% for result in all_ping_results if result.status == 'FAIL' %}
          {{ result.source }},{{ result.destination }},{{ result.status }}
          {% endfor %}
      run_once: true
