---
- name: Network Reachability Tests
  hosts: all
  gather_facts: false
  vars:
    target_hosts:  # Add your list of target IPs/hostnames here
      - 1.1.1.1
      - 10.0.70.20
      - 10.0.70.10
      - 10.0.70.11
      - 10.0.70.12
  tasks:
    - name: Test reachability from Cisco devices
      cisco.ios.ios_ping:
        dest: "{{ item }}"
        count: 5
        state: present
      loop: "{{ target_hosts }}"
      when: inventory_hostname in groups['cisco']

    - name: Test reachability from Linux servers
      ansible.builtin.command:
        cmd: "ping -c 5 -W 2 {{ item }}"
      register: ping_results
      loop: "{{ target_hosts }}"
      ignore_errors: yes
      changed_when: false
      when: inventory_hostname in groups['linux_servers']

    - name: Show ping results for Linux devices
      ansible.builtin.debug:
        var: ping_results.results[].stdout_lines
      when: 
        - inventory_hostname in groups['linux_servers']
        - ping_results is defined