---
- name: Solar Dynamics network ping test
  ignore_errors: true
  vars: 
    ipaddresses:
    - 1.1.1.1
    - 10.0.70.20
    - 10.0.70.10
    - 10.0.70.11
    - 10.0.70.12

    hostnames:
    - SD-HQ-WIN1.solardynamics.eu
    
  tasks:
    - name: Ping control node by IP
      hosts: cisco
      cisco.ios.ios_ping:
        dest: {{ item }}
      loop: {{ ipaddresses }}

    - name: Ping control node by IP
      hosts: linux_servers
      ping:
        dest: {{ item }}
      loop: {{ ipaddresses }}

    - name: Ping control node by IP
      hosts: linux_servers
      ping:
        dest: {{ item }}
      loop: hostnames
    
...

