---
- name: Ping all Linux servers
  hosts: linux_servers
  tasks:
    - name: Ping Linux servers
      ping:

- name: Ping all Windows servers
  hosts: windows_servers
  tasks:
    - name: Ping Windows servers
      win_ping:

- name: Ping all Cisco devices
  hosts: cisco
  tasks:
    - name: Ping Cisco devices
      ping:
...
