- name: Register inventory hosts to Ansible
  hosts: SD-HQ-NMS
  gather_facts: no
  vars:
    zabbix_host_group: "Linux servers"
    zabbix_template_name: "Template OS Linux"
    zabbix_username: "Zabbix"
    zabbix_password: "Solar-Dynamics-2025"
    zabbix_api_url: "http://zabbix.solardynamics.eu:8080/api_jsonrpc.php"
  tasks:
    - name: Set credentials for Zabbix API
      ansible.builtin.set_fact:
        ansible_user: "{{ zabbix_username }}"
        ansible_httpapi_pass: "{{ zabbix_password }}"

    - name: Register each host from inventory in Zabbix
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
      community.zabbix.zabbix_host:
        host_name: "{{ item }}"
        visible_name: "{{ hostvars[item].ansible_hostname | default(item) }}"
        host_groups: "{{ hostvars[item].group_names }}"
        link_templates:
          - "{{ zabbix_template_name }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            # Assumes fact gathering has been done on the target hosts. Adjust as needed.
            ip: "{{ hostvars[item].ansible_default_ipv4.address | default('') }}"
            port: "10050"
        state: present
      loop: "{{ groups['linux_servers'] }}"
      delegate_to: localhost
