- name: Register inventory hosts to Zabbix
  hosts: SD-HQ-NMS
  gather_facts: no
  vars:
    ansible_zabbix_url_path: "http://zabbix.solardynamics.eu:8080/api_jsonrpc.php"
    ansible_httpapi_validate_certs: false
    zabbix_username: "Admin"
    zabbix_password: "zabbix"
    zabbix_host_group: "Linux servers"
    zabbix_template_name: "Template OS Linux"
  tasks:
    - name: Register hosts in Zabbix
      community.zabbix.zabbix_host:
        http_login_user: "{{ zabbix_username }}"
        http_login_password: "{{ zabbix_password }}"
        host_name: "{{ item }}"
        visible_name: "{{ item }}"
        host_groups:
          - "{{ zabbix_host_group }}"
        link_templates:
          - "{{ zabbix_template_name }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ hostvars[item].ansible_host }}"
            dns: ""
            port: "10050"
        status: enabled
        state: present
      loop: "{{ groups['linux_servers'] }}"
      delegate_to: localhost  # Run from Ansible control node