- name: Register hosts in Zabbix
  hosts: SD-HQ-NMS
  gather_facts: no
  vars:
    zabbix_host_group: "Linux servers"
    zabbix_template_name: "Template OS Linux"

    zabbix_api_url: "http://zabbix.solardynamics.eu/api_jsonrpc.php"
    zabbix_username: "your_username"  # Replace with your Zabbix username
    zabbix_password: "your_password"  # Replace with your Zabbix password
  tasks:
    - name: Authenticate with Zabbix
      community.zabbix.zabbix_auth:
        server_url: "{{ zabbix_api_url }}"
        username: "{{ zabbix_username }}"
        password: "{{ zabbix_password }}"
      register: zabbix_auth

    - name: Register each host in Zabbix
      community.zabbix.zabbix_host:
        server_url: "{{ zabbix_api_url }}"
        auth: "{{ zabbix_auth.auth }}"
        host_name: "{{ item }}"
        visible_name: "{{ item }}"
        host_groups:
          - "{{ zabbix_host_group }}"
        link_templates:
          - "{{ zabbix_template_name }}"
        status: enabled
        state: present
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ hostvars[item].ansible_host }}"
            dns: ""
            port: "10050"
      loop: "{{ groups['linux_servers'] }}"
