- name: Register inventory hosts to Zabbix
  hosts: SD-HQ-NMS
  gather_facts: no
  vars:
    ansible_httpapi_validate_certs: false
    zabbix_template_name: "Template OS Linux"
    zabbix_api_token: "8bcddfb1672d63ed31830fc61dc9fcdc64962ec68e540448d46ded1211e9c99c"
    ansible_network_os: zabbix.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8080
    ansible_zabbix_url_path: ''

  tasks:
  # Currently not available because of major version upgrade
  #  - name: Create host groups
  #    zabbix.zabbix.zabbix_group:
  #      state: present
  #      host_groups:
  #        - Ansible
  #        - Cisco

  - name: Create host groups
    zabbix.zabbix.zabbix_hostgroup:
      hostgroups:
        - Ansible
        - Linux servers
        - Cisco
        - Routers
        - Switches
        - Multilayer Switches
        - Unknown
      state: present

  - name: Add Linux hosts to Zabbix
    become: false
    delegate_to: SD-HQ-NMS
    zabbix.zabbix.zabbix_host:
      host_name: "{{ item }}"
      visible_name: "{{ item }}"
      description: Generated by Ansible
      host_groups:
        - "Linux servers"
        - "Virtual machines"
        - "Ansible"
      link_templates:
        - "Linux by Zabbix agent active"
      inventory_mode: manual
      inventory_zabbix:
        location: "{{ hostvars[item].location }}"
      interfaces:
        - type: "agent"
          ip: "{{ hostvars[item].ansible_host }}"
          dns: "{{ item }}"
          port: "10050"
      status: enabled
      state: present
    loop: "{{ groups['linux_servers'] | difference(['SD-HQ-NMS']) }}"

  - name: Add Cisco hosts to Zabbix
    become: false
    delegate_to: SD-HQ-NMS
    zabbix.zabbix.zabbix_host:
        host_name: "{{ item }}"
        visible_name: "{{ item }}"
        description: "Generated by Ansible"
        host_groups:
          - "Cisco"
          - "Ansible"
          - "{{ 'Routers' if 'router' in hostvars[item].group_names else 'Switches' if 'switch' in hostvars[item].group_names else 'Multilayer Switches' if 'mls' in hostvars[item].group_names else 'Unknown' }}"
        link_templates:
          - "Cisco IOS by SNMP"
        inventory_mode: manual
        inventory_zabbix:
          location: "{{ hostvars[item].location }}"
        interfaces:
          - type: "snmp"
            ip: "{{ hostvars[item].ansible_host }}"
            port: "161"
            details:
              version: 3
              securitylevel: 'authPriv'
              securityname: "{{ hostvars[item].snmp_user }}"
              authpassphrase: "{{ hostvars[item].snmp_pass }}"
              authprotocol: "{{ hostvars[item].snmp_auth }}"
              privpassphrase: "{{ hostvars[item].snmp_privpass }}"
              privprotocol: "{{ hostvars[item].snmp_priv }}"
              max_repetitions: 10
              contextname: ''
              bulk: true
        status: enabled
        state: present
    loop: "{{ groups['cisco'] }}"

