---
- name: Install and configure Zabbix Agent on target hosts
  hosts: all
  gather_facts: yes
  become: true
  vars:
    zabbix_agent_package: "zabbix-agent"            # Package name for the agent
    zabbix_agent_conf_file: "/etc/zabbix/zabbix_agentd.conf"
  tasks:
    - name: Install Zabbix Agent on Debian-based systems
      apt:
        name: "{{ zabbix_agent_package }}"
        state: present

    - name: Deploy Zabbix Agent configuration file
      template:
        src: zabbix_agentd.conf.j2
        dest: "{{ zabbix_agent_conf_file }}"
        owner: root
        group: root
        mode: '0644'
      notify: Restart Zabbix Agent

    - name: Ensure Zabbix Agent service is started and enabled
      service:
        name: zabbix-agent
        state: started
        enabled: yes

  handlers:
    - name: Restart Zabbix Agent
      service:
        name: zabbix-agent
        state: restarted
