- name: Install Zabbix Agent
  become: true
  apt:
    name: "{{ zabbix_agent_package }}"
    state: present
    
- name: Ensure /var/log/zabbix/zabbix_agend.log file exists
  file:
    path: /var/log/zabbix/zabbix_agend.log
    state: touch
    owner: zabbix
    group: zabbix
    mode: '0644'

- name: Deploy Zabbix Agent configuration file
  become: true
  template:
    src: zabbix_agentd.conf.j2
    dest: "{{ zabbix_agent_conf_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Zabbix Agent

- name: Ensure Zabbix Agent service is started and enabled
  become: true
  service:
    name: zabbix-agent
    state: started
    enabled: yes