---
# Connections to Windows servers *MUST* use these rules to work.
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: ntlm
ansible_winrm_scheme: http
ansible_port: 5985
ansible_become_method: runas
ansible_become_user: Administrator
...
